from asciimatics.screen import ManagedScreen, Screen
from time import sleep


def test(screen): 
    screen.clear()
    screen.print_at('Starting', 0, 0)
    screen.refresh()
    sleep(2)
    # screen.clear()
    screen.print_at('RED', 1, 1, Screen.COLOUR_RED)
    screen.refresh()
    sleep(2)
    # screen.clear()
    screen.print_at('YELLOW', 2, 2, Screen.COLOUR_YELLOW)
    screen.refresh()
    sleep(2)
    # screen.clear()
    screen.print_at('GREEN', 3, 3, Screen.COLOUR_GREEN)
    screen.refresh()
    sleep(2)
    # screen.clear()
    screen.print_at('CYAN', 4, 4, Screen.COLOUR_CYAN)
    screen.refresh()
    sleep(2)
    # screen.clear()
    screen.print_at('BLUE', 5, 5, Screen.COLOUR_BLUE)
    screen.refresh()
    sleep(2)
    # screen.clear()
    screen.print_at('MAGENTA', 6, 6, Screen.COLOUR_MAGENTA)
    screen.refresh()
    sleep(2)
    # screen.clear()
    screen.print_at('BLACK', 7, 7, Screen.COLOUR_BLACK)
    screen.refresh()
    sleep(1)
    
    screen.print_at('THAT WAS BLACK', 7, 7, Screen.COLOUR_MAGENTA)
    screen.refresh()
    sleep(2)
    # screen.clear()
    screen.print_at('WHITE', 8, 8, Screen.COLOUR_WHITE)
    screen.refresh()
    # screen.clear()
    sleep(10)
    screen.clear()

Screen.wrapper(test)